[files]
extend-exclude = ["assets/vendor/", "assets/css/theme/figma/", "eslint.config.ts"]

[default]
locale = "en-us"
extend-ignore-re = ["lts-jod", "AxeBuilder", "axeResult"]

[default.extend-words]
behaviour = "behaviour"
initialise = "initialise"
