outputFolder: achecker-results

failLevels:
  - violation
  # - potentialviolation

reportLevels:
  - violation
  # - potentialviolation
  # - recommendation
  # - potentialrecommendation
  # - manual
